name: BuildFromMaster

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: false
    - name: Restore
      run: dotnet restore MbSoftLab.TemplateEngine.Core.sln
    - name: Build
      run: dotnet build MbSoftLab.TemplateEngine.Core.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test MbSoftLab.TemplateEngine.Core.sln --no-restore --verbosity normal
